name: "🔄 Sync Upstream"

on:
  schedule:
    - cron: "00 05 * * 1-5"
  workflow_dispatch:

jobs:
  sync-upstream-envoy-1-22:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.22"
      - name: Install Tools
        run: |
          go install k8s.io/test-infra/robots/pr-creator
      # NOTE: Istio 1.22.x: Envoy release/v1.30
      # https://istio.io/latest/docs/releases/supported-releases/
      - name: Run Automator
        env:
          AUTOMATOR_TOKEN: ${{ secrets.AUTOMATOR_TOKEN }}
        run: |
          export BUILD_WITH_CONTAINER="0"
          ./tools/automator-main.sh \
            --org=alauda-mesh \
            --repo=envoy \
            --branch=istio-1.22 \
            --token=${AUTOMATOR_TOKEN} \
            '--title=Automator: merge upstream changes to $AUTOMATOR_ORG/$AUTOMATOR_REPO@$AUTOMATOR_BRANCH' \
            "--labels=tide/merge-method-merge,auto-merge" \
            --modifier=merge_upstream_envoy_istio_1_22 \
            --merge-repository=https://github.com/envoyproxy/envoy \
            --merge-branch=release/v1.30 \
            --merge-strategy=merge

  sync-upstream-proxy-1-22:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.22"
      - name: Install Tools
        run: |
          go install k8s.io/test-infra/robots/pr-creator
      - name: Run Automator
        env:
          AUTOMATOR_TOKEN: ${{ secrets.AUTOMATOR_TOKEN }}
        run: |
          export BUILD_WITH_CONTAINER="0"
          ./tools/automator-main.sh \
            --org=alauda-mesh \
            --repo=proxy \
            --branch=istio-1.22 \
            --token=${AUTOMATOR_TOKEN} \
            '--title=Automator: merge upstream changes to $AUTOMATOR_ORG/$AUTOMATOR_REPO@$AUTOMATOR_BRANCH' \
            "--labels=tide/merge-method-merge,auto-merge" \
            --modifier=merge_upstream_proxy_release_1_22 \
            --merge-repository=https://github.com/istio/proxy \
            --merge-branch=release-1.22 \
            --merge-strategy=merge

  sync-upstream-istio-1-22:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.22"
      - name: Install Tools
        run: |
          go install k8s.io/test-infra/robots/pr-creator
      - name: Run Automator
        env:
          AUTOMATOR_TOKEN: ${{ secrets.AUTOMATOR_TOKEN }}
        run: |
          export BUILD_WITH_CONTAINER="0"
          ./tools/automator-main.sh \
            --org=alauda-mesh \
            --repo=istio \
            --branch=istio-1.22 \
            --token=${AUTOMATOR_TOKEN} \
            '--title=Automator: merge upstream changes to $AUTOMATOR_ORG/$AUTOMATOR_REPO@$AUTOMATOR_BRANCH' \
            "--labels=tide/merge-method-merge,auto-merge" \
            --modifier=merge_upstream_istio_release_1_22 \
            --merge-repository=https://github.com/istio/istio \
            --merge-branch=release-1.22 \
            --merge-strategy=merge
